name: Infra App Deloyement Pipeline

trigger: none 

pool: RaghavPool

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'TodoAppServiceConnection'