name: Infra App Deloyement Pipeline

trigger: none 

pool: RaghavPool

steps:
- task: TerraformInstaller@1
  displayName: Terraform tool install
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'TodoAppServiceConnection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'TodoAppServiceConnection'
    backendAzureRmResourceGroupName: 'TodoRg'
    backendAzureRmStorageAccountName: 'tfstorage1'
    backendAzureRmContainerName: 'tfcontainer'
    backendAzureRmKey: 'Infra.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'show'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    outputTo: 'console'
    outputFormat: 'default'
    environmentServiceNameAzureRM: 'TodoAppServiceConnection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'TodoAppServiceConnection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'TodoAppServiceConnection'


